const allowedStudentsPageStrings = {
  page: {
    title: "Manage Allowed Students",
    description: "Control which students are allowed to book office hours",
  },
  modals: {
    close: "Close",
    addTitle: "Add Allowed Student",
    editTitle: "Edit Allowed Student",
    deleteTitle: "Delete Allowed Student",
    statusTitle: "Booking Policy Settings",
  },
  buttons: {
    add: "Add Student",
    edit: "Edit",
    delete: "Delete",
    refresh: "Refresh",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    back: "Back",
    close: "Close",
  },
  forms: {
    firstName: "First Name",
    lastName: "Last Name",
    idNumber: "ID Number",
    email: "Email Address",
    placeholders: {
      firstName: "Enter first name",
      lastName: "Enter last name",
      idNumber: "Enter student ID",
      email: "Enter email address",
    },
    validation: {
      required: "This field is required",
      invalidEmail: "Invalid email address",
      duplicateEmail: "This email is already allowed",
      duplicateId: "This ID is already allowed",
    },
  },
  table: {
    title: "Allowed Students",
    empty: "No allowed students found",
    headers: {
      firstName: "First Name",
      lastName: "Last Name",
      idNumber: "ID Number",
      email: "Email",
      actions: "Actions",
    },
    studentsFound: "students",
    noResults: "No students match your search",
  },
  search: {
    placeholder: "Search by name, ID, or email...",
    label: "Search",
  },
  sort: {
    label: "Sort by",
    byName: "First Name",
    byEmail: "Email",
    byId: "ID Number",
  },
  status: {
    title: "Booking Policy Settings",
    description: "Configure who can book office hours for this slot",
    allowedOnly: "Only Allowed Students",
    allowedOnlyDesc: "Only students in the list above can book",
    allStudents: "All Students Allowed",
    allStudentsDesc: "Any student can book office hours",
    currentStatus: "Current Status",
    toggle: "Change Setting",
  },
  messages: {
    loading: "Loading...",
    adding: "Adding student...",
    updating: "Updating student...",
    deleting: "Deleting student...",
    success: "Operation completed successfully",
    addSuccess: "Student added successfully",
    editSuccess: "Student updated successfully",
    deleteSuccess: "Student deleted successfully",
    noSlotSelected: "Please select a slot first",
    selectSlot: "Select a slot to view or manage allowed students",
    error: "An error occurred. Please try again.",
    confirmDelete: "Are you sure you want to delete this student?",
    deleteWarning: "This action cannot be undone.",
  },
  slots: {
    title: "Select a Slot",
    selectPlaceholder: "Choose a slot",
    empty: "No slots available",
    noSlots: "Create a slot first to manage allowed students",
  },
  aria: {
    toggleNav: "Toggle navigation",
    openMenu: "Open menu",
    closeMenu: "Close menu",
  },
};

export default allowedStudentsPageStrings;
