const manageBookingsStrings = {
  en: {
    page: {
      title: "Manage Bookings",
      description: "View, update, or cancel your scheduled appointments",
      noBookings: "No bookings found",
      noBookingsDescription: "You don't have any bookings yet.",
    },
    filters: {
      status: "Status",
      course: "Slot",
      sortBy: "Sort By",
      filterByStatus: "Filter by Status",
      allBookings: "All Bookings",
      activeOnly: "Active Only",
      cancelledOnly: "Cancelled Only",
      completedOnly: "Completed Only",
      allCourses: "All Slots",
      byDate: "Date",
      byCourse: "Slot Name",
      dateRange: "Date Range",
      from: "From",
      to: "To",
      apply: "Apply Filters",
      clear: "Clear Filters",
      search: "Search by student name or email",
    },
    sections: {
      activeBookings: "Active Bookings",
      cancelledBookings: "Cancelled Bookings",
      completedBookings: "Completed Bookings",
    },
    bookingCard: {
      student: "Student",
      course: "Slot",
      section: "Section",
      date: "Date",
      time: "Time",
      duration: "Duration",
      room: "Room",
      status: "Status",
      bookedOn: "Booked on",
      actions: "Actions",
    },
    status: {
      active: "Active",
      cancelled: "Cancelled",
      completed: "✓ Completed",
    },
    buttons: {
      update: "Update",
      cancel: "Cancel",
      view: "View Details",
      confirmCancel: "Confirm Cancel",
      deleteAllCancelled: "Delete All Cancelled",
    },
    modals: {
      cancelTitle: "Cancel Booking",
      cancelMessage: "Are you sure you want to cancel this booking? This action cannot be undone.",
      cancelConfirmTitle: "Cancel Booking",
      cancelConfirmMessage: "Are you sure you want to cancel this booking? The student will be notified immediately.",
      keepBooking: "Keep Booking",
      confirmCancel: "Yes, Cancel",
      yes: "Yes, Cancel",
      no: "No, Keep It",
      updateTitle: "Update Booking",
      currentBooking: "Current Booking",
      selectNewDate: "Select New Date",
      selectNewTime: "Select New Time",
      noAvailableTimes: "No available times for this date",
      cancelButton: "Cancel",
      confirmUpdate: "Update Booking",
      studentNotified: "The student has been notified",
      errors: {
        noAvailableTimes: "Failed to load available times",
        selectDateAndTime: "Please select both date and time",
      },
    },
    messages: {
      success: "Booking cancelled successfully",
      error: "Failed to load bookings",
      cancelSuccess: "Booking cancelled successfully",
      cancelError: "Failed to cancel booking",
      updateSuccess: "Booking updated successfully",
      updateError: "Failed to update booking",
      clearedCancelled: "All cancelled bookings have been cleared from view",
      noActiveBookings: "No active bookings",
      noCancelledBookings: "No cancelled bookings",
      noCompletedBookings: "No completed bookings",
      loading: "Loading bookings...",
      noData: "No data available",
      canceling: "Cancelling booking...",
      updating: "Updating booking...",
    },
    table: {
      headers: {
        studentName: "Student Name",
        course: "Slot",
        date: "Date & Time",
        status: "Status",
        actions: "Actions",
      },
    },
    aria: {
      cancelBooking: "Cancel this booking",
      viewDetails: "View booking details",
      filterBookings: "Filter bookings",
    },
  },
  ar: {
    page: {
      title: "إدارة الحجوزات",
      description: "اعرض، عدّل، أو ألغِ مواعيدك المحجوزة",
      noBookings: "لا توجد حجوزات",
      noBookingsDescription: "ليس لديك أي حجوزات بعد.",
    },
    filters: {
      status: "الحالة",
      course: "الموعد",
      sortBy: "ترتيب حسب",
      filterByStatus: "تصفية حسب الحالة",
      allBookings: "جميع الحجوزات",
      activeOnly: "النشطة فقط",
      cancelledOnly: "الملغاة فقط",
      completedOnly: "المكتملة فقط",
      allCourses: "جميع المواعيد",
      byDate: "التاريخ",
      byCourse: "اسم الموعد",
      dateRange: "الفترة الزمنية",
      from: "من",
      to: "إلى",
      apply: "تطبيق",
      clear: "مسح الفلاتر",
      search: "البحث باسم الطالب أو البريد الإلكتروني",
    },
    sections: {
      activeBookings: "الحجوزات النشطة",
      cancelledBookings: "الحجوزات الملغاة",
      completedBookings: "الحجوزات المكتملة",
    },
    bookingCard: {
      student: "الطالب",
      course: "الموعد",
      section: "القسم",
      date: "التاريخ",
      time: "الوقت",
      duration: "المدة",
      room: "المكان",
      status: "الحالة",
      bookedOn: "تاريخ الحجز",
      actions: "الإجراءات",
    },
    status: {
      active: "نشط",
      cancelled: "ملغي",
      completed: "✓ مكتمل",
    },
    buttons: {
      update: "تعديل",
      cancel: "إلغاء",
      view: "عرض التفاصيل",
      confirmCancel: "تأكيد الإلغاء",
      deleteAllCancelled: "حذف جميع الملغاة",
    },
    modals: {
      cancelTitle: "إلغاء الحجز",
      cancelMessage: "هل أنت متأكد من رغبتك في إلغاء هذا الحجز؟ لا يمكن التراجع عن هذا الإجراء.",
      cancelConfirmTitle: "إلغاء الحجز",
      cancelConfirmMessage: "هل أنت متأكد من رغبتك في إلغاء هذا الحجز؟ سيتم إخطار الطالب فوراً.",
      keepBooking: "الاحتفاظ بالحجز",
      confirmCancel: "نعم، إلغاء الحجز",
      yes: "نعم، إلغاء",
      no: "لا، الاحتفاظ به",
      updateTitle: "تعديل الحجز",
      currentBooking: "الحجز الحالي",
      selectNewDate: "اختر تاريخاً جديداً",
      selectNewTime: "اختر وقتاً جديداً",
      noAvailableTimes: "لا توجد أوقات متاحة لهذا التاريخ",
      cancelButton: "إلغاء",
      confirmUpdate: "تأكيد التعديل",
      studentNotified: "تم إخطار الطالب",
      errors: {
        noAvailableTimes: "فشل تحميل الأوقات المتاحة",
        selectDateAndTime: "يرجى اختيار التاريخ والوقت",
      },
    },
    messages: {
      success: "تم إلغاء الحجز بنجاح",
      error: "فشل تحميل الحجوزات",
      cancelSuccess: "تم إلغاء الحجز بنجاح",
      cancelError: "فشل إلغاء الحجز",
      updateSuccess: "تم تعديل الحجز بنجاح",
      updateError: "فشل تعديل الحجز",
      clearedCancelled: "تم إزالة جميع الحجوزات الملغاة من العرض",
      noActiveBookings: "لا توجد حجوزات نشطة",
      noCancelledBookings: "لا توجد حجوزات ملغاة",
      noCompletedBookings: "لا توجد حجوزات مكتملة",
      loading: "جارٍ التحميل...",
      noData: "لا توجد بيانات متاحة",
      canceling: "جارٍ إلغاء الحجز...",
      updating: "جارٍ تعديل الحجز...",
    },
    table: {
      headers: {
        studentName: "اسم الطالب",
        course: "الموعد",
        date: "التاريخ والوقت",
        status: "الحالة",
        actions: "الإجراءات",
      },
    },
    aria: {
      cancelBooking: "إلغاء هذا الحجز",
      viewDetails: "عرض تفاصيل الحجز",
      filterBookings: "تصفية الحجوزات",
    },
  },
};

export default manageBookingsStrings;
