const manageBookingsStrings = {
  page: {
    title: "Manage Bookings",
    description: "View, update, or cancel your scheduled appointments",
    noBookings: "No bookings found",
    noBookingsDescription: "You don't have any bookings yet.",
  },
  filters: {
    status: "Status",
    course: "Slot",
    sortBy: "Sort By",
    filterByStatus: "Filter by Status",
    allBookings: "All Bookings",
    activeOnly: "Active Only",
    cancelledOnly: "Cancelled Only",
    completedOnly: "Completed Only",
    allCourses: "All Slots",
    byDate: "Date",
    byCourse: "Slot Name",
    dateRange: "Date Range",
    from: "From",
    to: "To",
    apply: "Apply Filters",
    clear: "Clear Filters",
    search: "Search by student name or email",
  },
  sections: {
    activeBookings: "Active Bookings",
    cancelledBookings: "Cancelled Bookings",
    completedBookings: "Completed Bookings",
  },
  bookingCard: {
    student: "Student",
    course: "Slot",
    section: "Section",
    date: "Date",
    time: "Time",
    duration: "Duration",
    room: "Room",
    status: "Status",
    bookedOn: "Booked on",
    actions: "Actions",
  },
  status: {
    active: "Active",
    cancelled: "Cancelled",
    completed: "✓ Completed",
  },
  buttons: {
    update: "Update",
    cancel: "Cancel",
    view: "View Details",
    confirmCancel: "Confirm Cancel",
    deleteAllCancelled: "Delete All Cancelled",
  },
  modals: {
    cancelTitle: "Cancel Booking",
    cancelMessage: "Are you sure you want to cancel this booking? This action cannot be undone.",
    cancelConfirmTitle: "Cancel Booking",
    cancelConfirmMessage: "Are you sure you want to cancel this booking? The student will be notified immediately.",
    keepBooking: "Keep Booking",
    confirmCancel: "Yes, Cancel",
    yes: "Yes, Cancel",
    no: "No, Keep It",
    updateTitle: "Update Booking",
    currentBooking: "Current Booking",
    selectNewDate: "Select New Date",
    selectNewTime: "Select New Time",
    noAvailableTimes: "No available times for this date",
    cancelButton: "Cancel",
    confirmUpdate: "Update Booking",
    studentNotified: "The student has been notified",
    errors: {
      noAvailableTimes: "Failed to load available times",
      selectDateAndTime: "Please select both date and time",
    },
  },
  messages: {
    success: "Booking cancelled successfully",
    error: "Failed to load bookings",
    cancelSuccess: "Booking cancelled successfully",
    cancelError: "Failed to cancel booking",
    updateSuccess: "Booking updated successfully",
    updateError: "Failed to update booking",
    clearedCancelled: "All cancelled bookings have been cleared from view",
    noActiveBookings: "No active bookings",
    noCancelledBookings: "No cancelled bookings",
    noCompletedBookings: "No completed bookings",
    loading: "Loading bookings...",
    noData: "No data available",
  },
  table: {
    headers: {
      studentName: "Student Name",
      course: "Slot",
      date: "Date & Time",
      status: "Status",
      actions: "Actions",
    },
  },
  aria: {
    cancelBooking: "Cancel this booking",
    viewDetails: "View booking details",
    filterBookings: "Filter bookings",
  },
};

export default manageBookingsStrings;
