const manageCoursesPageStrings = {
  pages: {
    create: "Create Slot",
    view: "View Slots",
    edit: "Edit Slots",
    delete: "Delete Slots",
  },

  // Create Slot Page Strings
  create: {
    title: "Create New Slot",
    description: "Add a new office hour slot to your schedule.",
    fields: {
      courseName: "Slot Name",
      section: "Section (Optional)",
      dayOfWeek: "Day of Week",
      room: "Room/Location",
      startTime: "Start Time",
      endTime: "End Time",
      duration: "Duration (minutes)",
      startDate: "Start Date",
      endDate: "End Date",
      studentLimit: "Student Limit per Slot (Optional)",
      csvFile: "Import Students (CSV)",
    },
    placeholders: {
      courseName: "e.g., CS 101 - Intro to Programming",
      section: "e.g., A1, B2",
      room: "e.g., Room 201",
      duration: "e.g., 60",
      studentLimit: "e.g., 1",
    },
    hints: {
      studentLimit: "Maximum number of students allowed per booking slot. Default is 1.",
    },
    csv: {
      label: "Import Students (CSV)",
      dragDrop: "Drag & drop a CSV file here, or click to browse",
      selectedFile: "Selected file:",
      removeFile: "Remove",
      hint: "CSV should contain columns: First name, Last name, ID number, Email address",
      optional: "Optional - You can add students later",
      uploading: "Uploading CSV...",
      uploadSuccess: "CSV uploaded successfully!",
      uploadError: "Failed to upload CSV.",
      studentsCreated: "students added",
      errors: "errors encountered",
    },
    dayOptions: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    buttons: {
      create: "Create Slot",
      creating: "Creating...",
    },
    success: "Slot created successfully!",
    errors: {
      courseNameRequired: "Slot name is required.",
      dayRequired: "Please select a day of week.",
      startTimeRequired: "Start time is required.",
      endTimeRequired: "End time is required.",
      startDateRequired: "Start date is required.",
      endDateRequired: "End date is required.",
      roomRequired: "Room/Location is required.",
      failed: "Failed to create slot. Please try again.",
    },
    recentSlots: "Recent Slots",
  },

  // View Slots Page Strings
  view: {
    title: "Your Slots",
    description: "View and manage all your office hour slots.",
    loading: "Loading your slots...",
    noSlots: "No Slots Yet",
    noSlotsDescription:
      "Use the Add Slot button to start building your schedule.",
    slotsFound: "slots found",
    sortBy: "Sort By",
    search: "Search",
    searchPlaceholder: "Search by slot name, section, or room",
    statusFilter: "Status",
    statusOptions: {
      all: "All",
      active: "Active",
      inactive: "Inactive",
    },
    sortOptions: {
      courseName: "Slot Name",
      dayOfWeek: "Day of Week",
      startTime: "Start Time",
    },
    section: "Section",
    day: "Day",
    time: "Time",
    room: "Room",
    studentLimit: "Student Limit",
    dates: "Dates",
    id: "ID",
    duration: "Duration (minutes)",
    createdAt: "Created At",
    actions: "Actions",
    listTitle: "Slot List",
    manageStudentsComingSoon: "Student management is coming soon.",
  
    to: "to",
    backToList: "Back to list",
    active: "Active",
    inactive: "Inactive",
    refresh: "Refresh",
    buttons: {
      edit: "Edit",
      delete: "Delete",
      activate: "Activate",
      deactivate: "Deactivate",
      toggling: "Toggling...",
      manageStudents: "Manage Allowed Students",
      addCourse: "Add Slot",
      saving: "Saving...",
      share: "Share",
    },
  },

  // Edit Slots Page Strings
  edit: {
    title: "Edit Slot",
    description: "Modify the details of your office hour slot.",
    selectASlot: "Select a Slot to Edit",
    selectDescription:
      "Choose a slot from the View Slots tab or select one below.",
    availableSlots: "Available Slots:",
    editing: "Currently Editing",
    deselectSlot: "Deselect",
    fields: {
      courseName: "Course Name",
      section: "Section (Optional)",
      dayOfWeek: "Day of Week",
      room: "Room/Location",
      startTime: "Start Time",
      endTime: "End Time",
      duration: "Duration (minutes)",
      startDate: "Start Date",
      endDate: "End Date",
      studentLimit: "Student Limit per Slot (Optional)",
    },
    placeholders: {
      duration: "e.g., 60",
      studentLimit: "e.g., 1",
    },
    hints: {
      studentLimit: "Maximum number of students allowed per booking slot.",
    },
    dayOptions: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    buttons: {
      update: "Update Slot",
      updating: "Updating...",
    },
    success: "Slot updated successfully!",
    errors: {
      noSlotSelected: "Please select a slot to edit.",
      courseNameRequired: "Slot name is required.",
      dayRequired: "Please select a day of week.",
      startTimeRequired: "Start time is required.",
      endTimeRequired: "End time is required.",
      startDateRequired: "Start date is required.",
      endDateRequired: "End date is required.",
      roomRequired: "Room/Location is required.",
      failed: "Failed to update slot. Please try again.",
    },
  },

  // Delete Slots Page Strings
  delete: {
    title: "Delete Slot",
    description: "Permanently remove a slot from your schedule.",
    selectASlot: "Select a Slot to Delete",
    selectDescription:
      "Choose a slot from the View Slots tab or select one below.",
    availableSlots: "Available Slots:",
    deselectSlot: "Deselect",
    confirmMessage: "Are you sure? This action cannot be undone.",
    warning: {
      title: "⚠️ Warning",
      message:
        "Deleting this slot will remove all associated information. Students with bookings will be notified.",
    },
    details: {
      section: "Section",
      day: "Day",
      time: "Time",
      room: "Room",
      dates: "Dates",
      to: "to",
    },
    buttons: {
      delete: "Delete Slot",
      confirmDelete: "Confirm Delete",
      deleting: "Deleting...",
      cancel: "Cancel",
    },
    success: "Slot deleted successfully!",
    errors: {
      noSlotSelected: "Please select a slot to delete.",
      failed: "Failed to delete slot. Please try again.",
    },
  },
  modals: {
    createTitle: "Create New Slot",
    editTitle: "Edit Slot",
    deleteTitle: "Delete Slot",
    manageStudentsTitle: "Manage Allowed Students",
    shareTitle: "Share Office Hour Slot",
    comingSoon: "This feature is coming soon.",
    close: "Close",
  },

  // Share Slot Strings
  share: {
    slotInfo: "Slot Information",
    shareLink: "Share Link",
    copyLink: "Copy Link",
    copiedToClipboard: "Copied!",
    linkCopiedMessage: "Link copied to clipboard!",
    copyError: "Failed to copy link. Please try again.",
    instructions: "How to share:",
    instruction1: "Copy the link above",
    instruction2: "Share it with students via email, messaging, or any platform",
    instruction3: "Students can click the link to book this office hour slot",
    errorNoTAId: "Error: Unable to determine TA ID",
  },

  // Warning Modal Strings
  warningModal: {
    editTitle: "Confirm Slot Edit",
    editMessage: "Editing this slot may affect existing student bookings. Changes to date, time, or duration may cancel related bookings.",
    editWarning: "This action might cancel some student bookings and could take a moment to process.",
    editConfirm: "Continue Editing",
    editCancel: "Cancel",

    deactivateTitle: "Confirm Slot Deactivation",
    deactivateMessage: "Deactivating this slot will cancel all active student bookings.",
    deactivateWarning: "All students with bookings will be notified about the cancellation. This process might take a while.",
    deactivateConfirm: "Deactivate Slot",
    deactivateCancel: "Cancel",

    activateMessage: "Activating this slot will make it available for new bookings.",
    activateWarning: "Make sure the slot details are correct before activating.",
    activateConfirm: "Activate Slot",
  },
};

export default manageCoursesPageStrings;
