const pendingBookingsStrings = {
  en: {
    page: {
      title: "Confirm Bookings",
      description: "Review and confirm pending student bookings",
      noBookings: "No pending bookings found",
      noBookingsDescription: "You don't have any pending bookings to confirm.",
      selectiveView: "Booking Details",
    },
    filters: {
      search: "Search by student name or email",
      allPending: "All Pending",
      refresh: "Refresh",
      backToManage: "Back to Manage Bookings",
    },
    bookingCard: {
      student: "Student",
      course: "Slot",
      section: "Section",
      date: "Date",
      time: "Time",
      duration: "Duration",
      room: "Room",
      status: "Status",
      bookedOn: "Booked on",
      reason: "Reason for Booking",
      noReason: "No reason provided",
    },
    buttons: {
      confirm: "Confirm",
      cancel: "Cancel",
      confirmBooking: "Confirm Booking",
      cancelBooking: "Cancel Booking",
      close: "Close",
    },
    modals: {
      confirmTitle: "Confirm Booking",
      confirmMessage: "Are you sure you want to confirm this booking? The student will be notified immediately.",
      cancelTitle: "Cancel Booking",
      cancelMessage: "Are you sure you want to cancel this booking? The student will be notified immediately.",
      yes: "Yes",
      no: "No",
    },
    messages: {
      success: "Booking confirmed successfully",
      cancelSuccess: "Booking cancelled successfully",
      error: "Failed to load bookings",
      confirmError: "Failed to confirm booking",
      cancelError: "Failed to cancel booking",
      confirming: "Confirming booking...",
      canceling: "Cancelling booking...",
      networkError: "Network error. Please check your connection.",
      serverError: "Server error. Please try again later.",
    },
    status: {
      pending: "Pending",
      confirmed: "Confirmed",
      cancelled: "Cancelled",
    },
    table: {
      headers: {
        studentName: "Student Name",
        email: "Email",
        course: "Slot",
        dateTime: "Date & Time",
        reason: "Reason",
        actions: "Actions",
      },
    },
    aria: {
      confirmBooking: "Confirm this booking",
      cancelBooking: "Cancel this booking",
      expandBookingDetails: "Expand booking details",
    },
  },
  ar: {
    page: {
      title: "تأكيد الحجوزات",
      description: "مراجعة وتأكيد حجوزات الطلاب المعلقة",
      noBookings: "لم يتم العثور على حجوزات معلقة",
      noBookingsDescription: "ليس لديك أي حجوزات معلقة للتأكيد.",
      selectiveView: "تفاصيل الحجز",
    },
    filters: {
      search: "ابحث باسم الطالب أو البريد الإلكتروني",
      allPending: "جميع المعلقة",
      refresh: "تحديث",
      backToManage: "العودة إلى إدارة الحجوزات",
    },
    bookingCard: {
      student: "الطالب",
      course: "الموعد",
      section: "القسم",
      date: "التاريخ",
      time: "الوقت",
      duration: "المدة",
      room: "الغرفة",
      status: "الحالة",
      bookedOn: "تم الحجز في",
      reason: "سبب الحجز",
      noReason: "لم يتم تقديم سبب",
    },
    buttons: {
      confirm: "تأكيد",
      cancel: "إلغاء",
      confirmBooking: "تأكيد الحجز",
      cancelBooking: "إلغاء الحجز",
      close: "إغلاق",
    },
    modals: {
      confirmTitle: "تأكيد الحجز",
      confirmMessage: "هل أنت متأكد من رغبتك في تأكيد هذا الحجز؟ سيتم إخطار الطالب فوراً.",
      cancelTitle: "إلغاء الحجز",
      cancelMessage: "هل أنت متأكد من رغبتك في إلغاء هذا الحجز؟ سيتم إخطار الطالب فوراً.",
      yes: "نعم",
      no: "لا",
    },
    messages: {
      success: "تم تأكيد الحجز بنجاح",
      cancelSuccess: "تم إلغاء الحجز بنجاح",
      error: "فشل تحميل الحجوزات",
      confirmError: "فشل تأكيد الحجز",
      cancelError: "فشل إلغاء الحجز",
      confirming: "جاري تأكيد الحجز...",
      canceling: "جاري إلغاء الحجز...",
      networkError: "خطأ في الشبكة. يرجى التحقق من الاتصال.",
      serverError: "خطأ في الخادم. يرجى المحاولة لاحقاً.",
    },
    status: {
      pending: "قيد الانتظار",
      confirmed: "مؤكد",
      cancelled: "ملغى",
    },
    table: {
      headers: {
        studentName: "اسم الطالب",
        email: "البريد الإلكتروني",
        course: "الموعد",
        dateTime: "التاريخ والوقت",
        reason: "السبب",
        actions: "الإجراءات",
      },
    },
    aria: {
      confirmBooking: "تأكيد هذا الحجز",
      cancelBooking: "إلغاء هذا الحجز",
      expandBookingDetails: "توسيع تفاصيل الحجز",
    },
  },
};

export default pendingBookingsStrings;
