const profilePageStrings = {
  en: {
    profilePage: {
      title: "Profile",
      description: "Update your profile information below.",
      personalInformation: "Personal Information",
      username: "Username",
      firstName: "First name",
      lastName: "Last name",
      email: "Email",
      save: "Save",
      saving: "Saving...",
      resetPassword: "Reset Password",
      success: "Profile updated successfully",
      unexpectedError: "Unexpected response from server",
      failed: "Failed to update",
      verified: "Verified",
      instructor: "Instructor",
      student: "Student",
      change: "Change",
      changePassword: "Change Password",
    },
    emailModal: {
      title: "Change Email Address",
      newEmail: "New Email Address",
      confirmEmail: "Confirm Email Address",
      newEmailRequired: "New email is required",
      invalidEmail: "Invalid email format",
      emailMustDiffer: "New email must be different from current email",
      confirmEmailRequired: "Please confirm your email",
      emailsDoNotMatch: "Emails do not match",
      importantNotice: "Important:",
      verificationNotice: "A verification email will be sent to your new address. You must verify it to complete the change.",
      cancel: "Cancel",
      sending: "Sending...",
      sendVerification: "Send Verification",
      successMessage: "Verification email sent! Please check your inbox.",
      errorMessage: "Failed to request email change. Please try again.",
    },
    passwordModal: {
      title: "Change Password",
      currentPassword: "Current Password",
      newPassword: "New Password",
      confirmPassword: "Confirm Password",
      currentPasswordRequired: "Current password is required",
      newPasswordRequired: "New password is required",
      passwordMinLength: "Password must be at least 8 characters",
      passwordUppercase: "Password must contain at least one uppercase letter",
      passwordLowercase: "Password must contain at least one lowercase letter",
      passwordNumber: "Password must contain at least one number",
      confirmPasswordRequired: "Please confirm your password",
      passwordsDoNotMatch: "Passwords do not match",
      cancel: "Cancel",
      changing: "Changing...",
      changePassword: "Change Password",
      successMessage: "Password changed successfully!",
      errorMessage: "Failed to change password. Please try again.",
      requirements: "Password Requirements:",
      requirement1: "At least 8 characters",
      requirement2: "One uppercase letter",
      requirement3: "One lowercase letter",
      requirement4: "One number",
    },
  },
  ar: {
    profilePage: {
      title: "الملف الشخصي",
      description: "حدّث معلومات ملفك الشخصي أدناه.",
      personalInformation: "المعلومات الشخصية",
      username: "اسم المستخدم",
      firstName: "الاسم الأول",
      lastName: "الاسم الأخير",
      email: "البريد الإلكتروني",
      save: "حفظ",
      saving: "جاري الحفظ...",
      resetPassword: "إعادة تعيين كلمة المرور",
      success: "تم تحديث الملف الشخصي بنجاح",
      unexpectedError: "استجابة غير متوقعة من الخادم",
      failed: "فشل التحديث",
      verified: "مؤكد",
      instructor: "مدرس",
      student: "طالب",
      change: "تغيير",
      changePassword: "تغيير كلمة المرور",
    },
    emailModal: {
      title: "تغيير عنوان البريد الإلكتروني",
      newEmail: "عنوان البريد الإلكتروني الجديد",
      confirmEmail: "تأكيد عنوان البريد الإلكتروني",
      newEmailRequired: "البريد الإلكتروني الجديد مطلوب",
      invalidEmail: "صيغة بريد إلكتروني غير صالحة",
      emailMustDiffer: "يجب أن يكون البريد الإلكتروني الجديد مختلفًا عن البريد الحالي",
      confirmEmailRequired: "يرجى تأكيد بريدك الإلكتروني",
      emailsDoNotMatch: "عناوين البريد الإلكتروني غير متطابقة",
      importantNotice: "مهم:",
      verificationNotice: "سيتم إرسال بريد إلكتروني للتحقق إلى عنوانك الجديد. يجب عليك التحقق منه لإكمال التغيير.",
      cancel: "إلغاء",
      sending: "جاري الإرسال...",
      sendVerification: "إرسال التحقق",
      successMessage: "تم إرسال بريد التحقق! يرجى فحص بريدك الوارد.",
      errorMessage: "فشل طلب تغيير البريد الإلكتروني. يرجى المحاولة مرة أخرى.",
    },
    passwordModal: {
      title: "تغيير كلمة المرور",
      currentPassword: "كلمة المرور الحالية",
      newPassword: "كلمة المرور الجديدة",
      confirmPassword: "تأكيد كلمة المرور",
      currentPasswordRequired: "كلمة المرور الحالية مطلوبة",
      newPasswordRequired: "كلمة المرور الجديدة مطلوبة",
      passwordMinLength: "يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل",
      passwordUppercase: "يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل",
      passwordLowercase: "يجب أن تحتوي كلمة المرور على حرف صغير واحد على الأقل",
      passwordNumber: "يجب أن تحتوي كلمة المرور على رقم واحد على الأقل",
      confirmPasswordRequired: "يرجى تأكيد كلمة المرور",
      passwordsDoNotMatch: "كلمات المرور غير متطابقة",
      cancel: "إلغاء",
      changing: "جاري التغيير...",
      changePassword: "تغيير كلمة المرور",
      successMessage: "تم تغيير كلمة المرور بنجاح!",
      errorMessage: "فشل تغيير كلمة المرور. يرجى المحاولة مرة أخرى.",
      requirements: "متطلبات كلمة المرور:",
      requirement1: "على الأقل 8 أحرف",
      requirement2: "حرف كبير واحد",
      requirement3: "حرف صغير واحد",
      requirement4: "رقم واحد",
    },
  },
};

export default profilePageStrings;
